# game_data.py

# game_data.py

data = [
    {'name': 'Cristiano Ronaldo', 'follower_count': 500, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Ariana Grande', 'follower_count': 380, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 345, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 375, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower_count': 420, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 450, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Kim Kardashian', 'follower_count': 290, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 280, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 315, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Taylor Swift', 'follower_count': 310, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 260, 'description': 'Model', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 240, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Shakira', 'follower_count': 200, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Billie Eilish', 'follower_count': 105, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 230, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 100, 'description': 'Comedian and TV host', 'country': 'United States'},
    {'name': 'Will Smith', 'follower_count': 120, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 230, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Katy Perry', 'follower_count': 110, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Vin Diesel', 'follower_count': 95, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Chris Hemsworth', 'follower_count': 90, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'LeBron James', 'follower_count': 100, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Cardi B', 'follower_count': 130, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Lady Gaga', 'follower_count': 90, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Tom Holland', 'follower_count': 85, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Kevin Hart', 'follower_count': 120, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 100, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Drake', 'follower_count': 180, 'description': 'Rapper', 'country': 'Canada'},
    {'name': 'Khabib Nurmagomedov', 'follower_count': 80, 'description': 'MMA fighter', 'country': 'Russia'},
    {'name': 'David Beckham', 'follower_count': 75, 'description': 'Former footballer', 'country': 'United Kingdom'},
    {'name': 'Priyanka Chopra', 'follower_count': 85, 'description': 'Actress and producer', 'country': 'India'},
    {'name': 'Virat Kohli', 'follower_count': 190, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Chris Evans', 'follower_count': 60, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Robert Downey Jr.', 'follower_count': 55, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Hugh Jackman', 'follower_count': 50, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Shawn Mendes', 'follower_count': 100, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Gal Gadot', 'follower_count': 75, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Jason Momoa', 'follower_count': 45, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Emma Watson', 'follower_count': 60, 'description': 'Actress and activist', 'country': 'United Kingdom'},
    {'name': 'Mark Wahlberg', 'follower_count': 40, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 200, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Ed Sheeran', 'follower_count': 150, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'Gigi Hadid', 'follower_count': 70, 'description': 'Model', 'country': 'United States'},
    {'name': 'Blake Lively', 'follower_count': 50, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Zac Efron', 'follower_count': 55, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Ryan Reynolds', 'follower_count': 85, 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Margot Robbie', 'follower_count': 45, 'description': 'Actress', 'country': 'Australia'},
    {'name': 'Bruno Mars', 'follower_count': 85, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Dua Lipa', 'follower_count': 85, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'Maluma', 'follower_count': 90, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Millie Bobby Brown', 'follower_count': 55, 'description': 'Actress', 'country': 'United Kingdom'},
    {'name': 'Camila Cabello', 'follower_count': 65, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Shawn Johnson', 'follower_count': 10, 'description': 'Olympic gymnast', 'country': 'United States'},
    {'name': 'Simone Biles', 'follower_count': 12, 'description': 'Olympic gymnast', 'country': 'United States'},
    {'name': 'Lewis Hamilton', 'follower_count': 50, 'description': 'Formula 1 driver', 'country': 'United Kingdom'},
    {'name': 'Usain Bolt', 'follower_count': 20, 'description': 'Olympic sprinter', 'country': 'Jamaica'},
    {'name': 'Conor McGregor', 'follower_count': 45, 'description': 'MMA fighter', 'country': 'Ireland'},
    {'name': 'Serena Williams', 'follower_count': 35, 'description': 'Tennis player', 'country': 'United States'},
    {'name': 'Novak Djokovic', 'follower_count': 25, 'description': 'Tennis player', 'country': 'Serbia'},
    {'name': 'Maria Sharapova', 'follower_count': 20, 'description': 'Tennis player', 'country': 'Russia'},
    {'name': 'Tom Brady', 'follower_count': 30, 'description': 'American football quarterback', 'country': 'United States'},
    {'name': 'Roger Federer', 'follower_count': 40, 'description': 'Tennis player', 'country': 'Switzerland'},
    {'name': 'Tiger Woods', 'follower_count': 15, 'description': 'Golfer', 'country': 'United States'},
    {'name': 'Emma Stone', 'follower_count': 50, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Scarlett Johansson', 'follower_count': 60, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Brad Pitt', 'follower_count': 25, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Angelina Jolie', 'follower_count': 20, 'description': 'Actress', 'country': 'United States'},
    {'name': 'George Clooney', 'follower_count': 15, 'description': 'Actor and filmmaker', 'country': 'United States'}
]
